import assert from 'node:assert/strict';
import * as api from '../src/library/api';
import { VariantLifecycleController, defaultCarderVariant, lifecycleError, type LifecycleDependencies, type LifecycleEntry } from '../src/library/variant-lifecycle-state';
import type { LibraryVariantDetail, LibraryVariantsResponse, VariantLifecyclePreview } from '../src/library/model';
const variant = (id:string):LibraryVariantDetail=>({variant_id:id,card_id:'c',variant_key:id,display_label:id,
    standard:{state:'INCOMPLETE',sources:[]},overframe:{state:'INCOMPLETE',sources:[]},roles:{BS:{slot_state:'MISSING',asset:null,issues:[]},BG:{slot_state:'EMPTY',asset:null,issues:[]},OF:{slot_state:'EMPTY',asset:null,issues:[]}}});
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v));
const harness=(operation:LifecycleEntry['operation']='RENAME')=>{
    let state:LibraryVariantsResponse={card_id:'c',preferred_variant_id:'v',expected_state_token:'state',variants:[variant('v'),variant('other')]};
    const calls:{method:string;args?:unknown}[]=[];let failure:string|null=null;let collision=false;
    const preview=(operation:'RENAME'|'REMOVE'):VariantLifecyclePreview=>({operation,expected_state_token:'preview',preferred:true,can_execute:!collision,collision,
        recovery_policy:'PRESERVE_PREVIOUS_STATE',managed_assets:[],unmanaged_assets:[],proposed:{variant_key:'normalized',display_label:'Server label'},acknowledge_preferred_clear_required:operation==='REMOVE'});
    const result=(operation:string)=>({...clone(state),operation,changed:true});
    const reject=()=>{if(failure)throw new api.LibraryHttpError({status:409,code:failure,message:'injected'});};
    const client:LifecycleDependencies={getLibraryVariants:async()=>{calls.push({method:'state'});return clone(state);},refreshResolutionState:async()=>{calls.push({method:'refresh'});state.expected_state_token='fresh';return {} as any;},
        setPreferredVariant:async(card,id,token)=>{calls.push({method:'preferred',args:{card,id,token}});reject();state.preferred_variant_id=id;return result('PREFERRED');},
        previewVariantRename:async(id,body)=>{calls.push({method:'renamePreview',args:{id,body}});return preview('RENAME');},
        previewVariantRemove:async(id)=>{calls.push({method:'removePreview',args:id});return preview('REMOVE');},
        renameVariant:async(id,body)=>{calls.push({method:'rename',args:{id,body}});reject();return result('RENAME');},
        removeVariant:async(id,body)=>{calls.push({method:'remove',args:{id,body}});reject();state.variants=state.variants.filter(v=>v.variant_id!==id);return result('REMOVE');},};
    const controller=new VariantLifecycleController({cardId:'c',variantId:'v',operation},client);
    controller.onChanged=async()=>{calls.push({method:'views'});};controller.onBlocked=async()=>{calls.push({method:'blocked'});};
    return {controller,calls,get state(){return state;},fail:(code:string)=>{failure=code;},clear:()=>{failure=null;},collide:()=>{collision=true;}};
};
export async function runVariantLifecycleChecks(){
    let count=0;const check=async(name:string,run:()=>void|Promise<void>)=>{await run();count++;console.log(`RUN013 ${name} PASS`);};
    await check('Open in Carder Preferred uses identity and keeps broken Preferred selected',()=>{const a=variant('a');const b=variant('b');assert.equal(defaultCarderVariant([a,b],'b'),'b');assert.equal(b.standard.state,'INCOMPLETE');});
    await check('Sole variant with null preference is convenience only; no persistence call',()=>assert.equal(defaultCarderVariant([variant('a')],null),'a'));
    await check('Multiple null preference variants have no array-order default',()=>assert.equal(defaultCarderVariant([variant('a'),variant('b')],null),''));
    await check('Absent Preferred identity never silently falls back to sole variant',()=>assert.equal(defaultCarderVariant([variant('a')],'missing'),''));
    await check('Open reads state only, no scan/mutation and exact proposal from server',async()=>{const h=harness();await h.controller.load();assert.deepEqual(h.calls,[{method:'state'}]);assert.equal(h.controller.view.proposal.variant_key,'v');});
    await check('Preview/cancel cannot execute; confirm requires review',async()=>{const h=harness();await h.controller.load();await h.controller.confirm();await h.controller.review();assert.equal(h.controller.cancel(),true);await h.controller.confirm();assert.deepEqual(h.calls.map(c=>c.method),['state','renamePreview']);});
    await check('Rename server-normalized proposal and opaque preview token are frozen for execution',async()=>{const h=harness();await h.controller.load();h.controller.edit({variant_key:' ＦＯＯ ',display_label:'Label'});await h.controller.review();await h.controller.confirm();assert.deepEqual(h.calls.find(c=>c.method==='rename')?.args,{id:'v',body:{variant_key:'normalized',display_label:'Server label',expected_state_token:'preview'}});});
    await check('Proposal edit invalidates confirmation/token and cannot replay',async()=>{const h=harness();await h.controller.load();await h.controller.review();h.controller.edit({display_label:'edited'});await h.controller.confirm();assert.equal(h.calls.some(c=>c.method==='rename'),false);assert.equal(h.controller.view.preview,null);});
    await check('Collision preview remains visible but prevents execution',async()=>{const h=harness();await h.controller.load();h.collide();await h.controller.review();await h.controller.confirm();assert.equal(h.controller.view.preview?.collision,true);assert.match(h.controller.view.error!,/VARIANT_KEY_CONFLICT/);assert.equal(h.calls.some(c=>c.method==='rename'),false);});
    for(const operation of ['PREFERRED','CLEAR'] as const)await check(`${operation} sends target/null with authoritative token, refreshes only after success`,async()=>{const h=harness(operation);await h.controller.load();await h.controller.review();assert.equal(h.calls.some(c=>c.method==='preferred'),false);await h.controller.confirm();assert.deepEqual(h.calls.find(c=>c.method==='preferred')?.args,{card:'c',id:operation==='CLEAR'?null:'v',token:'state'});assert.equal(h.calls.at(-1)?.method,'views');assert.equal(h.calls.some(c=>c.method==='refresh'),false);});
    await check('Remove Preferred requires separate clear acknowledgement before confirmation',async()=>{const h=harness('REMOVE');await h.controller.load();await h.controller.review();await h.controller.confirm();assert.match(h.controller.view.error!,/PREFERRED_CLEAR_ACK_REQUIRED/);assert.equal(h.calls.some(c=>c.method==='remove'),false);h.controller.edit({},true);await h.controller.review();await h.controller.confirm();assert.deepEqual(h.calls.find(c=>c.method==='remove')?.args,{id:'v',body:{expected_state_token:'preview',acknowledge_preferred_clear:true}});});
    await check('Stale lifecycle refreshes context and requires new review; no automatic replay',async()=>{const h=harness();await h.controller.load();h.controller.edit({display_label:'Retained'});await h.controller.review();h.fail('VARIANT_STATE_STALE');await h.controller.confirm();assert.equal(h.controller.view.phase,'STALE');assert.equal(h.controller.view.proposal.display_label,'Retained');assert.equal(h.controller.view.state?.expected_state_token,'fresh');const n=h.calls.length;await h.controller.confirm();assert.equal(h.calls.length,n);assert.ok(h.calls.some(c=>c.method==='refresh'));h.clear();await h.controller.review();await h.controller.confirm();assert.equal(h.calls.filter(c=>c.method==='rename').length,2);});
    await check('Preview never optimistically changes variants/readiness',async()=>{const h=harness();await h.controller.load();const before=clone(h.controller.view.state);await h.controller.review();assert.deepEqual(h.controller.view.state,before);});
    for(const code of ['VARIANT_MUTATION_RECOVERY_REQUIRED','WORKSPACE_NOT_READY'])await check(`${code} persistently blocks lifecycle and calls Workspace block callback`,async()=>{const h=harness();await h.controller.load();await h.controller.review();h.fail(code);await h.controller.confirm();assert.equal(h.controller.view.phase,'RECOVERY_BLOCKED');assert.equal(h.controller.view.state,null);await h.controller.review();await h.controller.confirm();assert.equal(h.calls.filter(c=>c.method==='rename').length,1);assert.equal(h.calls.filter(c=>c.method==='blocked').length,1);});
    await check('All lifecycle semantic errors remain distinct',()=>{const codes=['VARIANT_NOT_FOUND','VARIANT_STATE_STALE','VARIANT_CARD_MISMATCH','VARIANT_KEY_INVALID','VARIANT_KEY_CONFLICT','VARIANT_DESTINATION_OCCUPIED','VARIANT_PATH_UNSAFE','PREFERRED_CLEAR_ACK_REQUIRED','VARIANT_MUTATION_FAILED','VARIANT_MUTATION_RECOVERY_REQUIRED','WORKSPACE_MAINTENANCE_ACTIVE','WORKSPACE_NOT_READY'];assert.equal(new Set(codes.map(code=>lifecycleError(new api.LibraryHttpError({status:422,code,message:code})))).size,codes.length);});
    await check('Lifecycle API paths/bodies preserve exact target, token, acknowledgement and HTTP errors',async()=>{
        const old=globalThis.fetch;const calls:any[]=[];globalThis.fetch=(async(url:any,init:any)=>{calls.push({url:String(url),method:init.method,body:init.body?JSON.parse(init.body):null});return new Response(JSON.stringify({code:'VARIANT_PATH_UNSAFE',message:'rejected'}),{status:422});}) as typeof fetch;
        try{for(const request of [()=>api.setPreferredVariant('c space','v','opaque'),()=>api.previewVariantRename('v space',{variant_key:'Ｖ',display_label:'V'}),()=>api.renameVariant('v',{variant_key:'new',display_label:'New',expected_state_token:'opaque'}),()=>api.previewVariantRemove('v'),()=>api.removeVariant('v',{expected_state_token:'opaque',acknowledge_preferred_clear:true})])await assert.rejects(request(),(e:any)=>e.code==='VARIANT_PATH_UNSAFE'&&e.status===422);
        assert.ok(calls[0].url.includes('c%20space'));assert.equal(calls[0].body.preferred_variant_id,'v');assert.equal(calls[1].body.variant_key,'Ｖ');assert.equal(calls[4].body.acknowledge_preferred_clear,true);assert.ok(calls.every(c=>c.method==='POST'));}finally{globalThis.fetch=old;}
    });
    console.log(`Library RUN 013 lifecycle checks: ${count} PASS / 0 FAIL / 0 SKIP`);
}
